server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5433/inventory_db}
    username: ${INVENTORY_DB_USERNAME:postgres}
    password: ${INVENTORY_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.vishal.ordering.common.event
        spring.json.use.type.headers: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
